### ISSUE TITLE
Spamming emotes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#452] opened 2019-09-16 14:12 UTC
There is no cooldown on user generated emotes, so it's possible to spam them by alternating emotes.

Especially the whistling and ill emote that make sound and can get annoying really fast.

**Comment by trevorhackman** [comment] 2019-09-16 15:03
Duplicate of #264

**Comment by jasonrohrer** [comment] 2019-09-20 19:31
Closed as dupe

**Closed by jasonrohrer** 2019-09-20 19:31 UTC
