### ISSUE TITLE
ability to remove empty bear caves

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLifeData7#1044] opened 2023-07-19 04:49 UTC
It would be nice to be able to remove an empty bear cave after the bear is killed. 

Mostly for highway purposes, as it is they can be routed around with paver arrows, and there is kind of an annoying case where you can get the paver stuck in one( you may have somewhat fixed that, I forget the exact details but there used to be a way to permanently get the paver stuck in an unrecoverable fashion, however I was able to pull out a recent case I found after hammering) 

Being able to do highway in an uncompromising straight line would be kind of satisfying though.

**Comment by TwistedHBG** [comment] 2023-07-19 10:59
Duplicate of #908

**Comment by jasonrohrer** [comment] 2023-07-19 12:09
I want there to be some crooked roads, sometimes.  Bear caves are like mountains that you have to go around.  They aren't that common.... I'm sure there are long stretches of straight roads possible.  But every once in a while, you get that hair-pin turn around the bear cave.

Also, I spent all that time drawing those pretty curved road tiles!

I'm pretty sure the stuck paver thing is fixed.

**Closed by jasonrohrer** 2023-07-19 12:09 UTC
