### ISSUE TITLE
Bug: Cart irretrievable after dropping

### ISSUE THREAD

**Issue by tatianaanthony** [jasonrohrer/OneLifeData7#606] opened 2020-01-21 22:41 UTC
I found a situation in which entering an uninhabitable zone with a cart leaves the cart irretrievable.  See image.
![IMG_2085](https://user-images.githubusercontent.com/9399133/72849104-04a4bf00-3c74-11ea-9cd3-88eeb320b3a3.JPG)

Expected behavior:  Entering an uninhabitable biome drops anything you're holding.  Those objects appear on the ground in the last cell that you occupied in an inhabitable biome before entering the uninhabitable biome.  It is possible to retrieve your item.

Actual behavior:  Entering the jungle biome with a cart (when the area entered was mostly surrounded by other items) results in the cart remaining in the jungle biome, in a spot that is unreachable.  

Version:  The Baby Placement Update, on Windows 10.  Playing through Steam.

Other notes: 

I started between the two tables to the north, and did a click-hold on the bottom edge of the screen to route me south.  It took me through the jungle peninsula there.  You may notice items to the south, southwest, and west of the jungle peninsula.

I believe this is a bug with how the location of an object dropped by biome sickness is chosen (though I don't know enough about the code to find that and confirm whether I'm right).

**Comment by jasonrohrer** [comment] 2020-01-24 17:47
Dupe of:

https://github.com/jasonrohrer/OneLife/issues/479

**Closed by jasonrohrer** 2020-01-24 17:47 UTC
