### ISSUE TITLE
Carts become derailed if they aren't in loaded areas*

### ISSUE THREAD

**Issue by Nika50501** [jasonrohrer/OneLifeData7#781] opened 2020-05-08 10:26 UTC
I made a 100 block looping rail and sent down six carts on it with 3-6 blocks between the carts. Eventually all carts became derailed next to each other (I moved in and out of the area quite a lot and there were no other players there at the time). I don't know for certain, but my guess is that one cart stops because its out of player "active chunk distance", then the other carts pile up on it and get derailed. Eventually the first carts gets reloaded and loops around and gets derailed as well. (I'm not sure how much processing power it would take but definitely carts shouldn't stop moving once they are out of player view distance since their main purpose it to transport things over long distance between villages and towns)

**Comment by jasonrohrer** [comment] 2020-05-12 20:19
Multiple carts on the same line isn't really an expected use case.  Actually, even looping tracks isn't intended.  You can only achieve that by kinda "hacking" track construction, and replacing tracks to complete the loop while the cart is already running.

In terms of carts moving off-screen, they do that correctly.  I just tested it with a cart that went 70+ tiles away and then looped back to to me, and it worked fine.

As to what's happening with the carts crashing, my guess is that some kind of timing issues are eventually accumulating, thus shrinking the gaps between your carts randomly, and eventually the gaps are reduced to zero, and they crash.

For example, as you walk back and forth, sometimes you "look" at the map, causing a cart tile to be fetched, and perhaps triggering an update for that cart a second before it happens for the others.  That would cause that cart to catch up by one tile.

I'll see if I can reproduce it, though...

**Comment by jasonrohrer** [comment] 2020-05-12 20:30
Any more details here?

Which server were you on?  Were you online the whole time, or did you die and come back later?

Were they running for a long time with absolutely no one looking a them (no one living nearby)?

Did this ever cross the boundary of a server restart?  That could definitely cause some problems, I think, because they wouldn't start moving again until someone walked over to look at them, and one might start before the others.

**Comment by jasonrohrer** [comment] 2020-05-12 20:57
One way I can reproduce is across a server restart.

After restart, moving objects don't start moving again until they are seen by someone.

If someone walks into the area slowly, they will "see" (load) one of the carts before the others.  That cart will start moving, and eventually crash into the others that haven't started moving yet.


But as long as the server is still online, they seem to keep moving forever....


I think that what's happening is that the map step time happens based on a server sleep, which isn't exact.  Every once in a while, this will happen after the second boundary that it's supposed to happen on, causing objects to make their moves one second late.

Meanwhile, if you're walking back and forth, you're loading parts of the map BETWEEN second boundaries (whenever you move).  This sometimes happens right after a second boundary, causing an object to make its move right away.  Meanwhile, the other nearby objects (which you didn't walk close enough to see), don't get their step until the map step happens 1 second late (due to server sleep timing).  So one cart gets one tile out of sync with the others.

If you walk around enough, this will happen often enough that it will eventually accumulate, and it will crash.

You might be able to see this happening, if this is the actual problem, by periodically looking at your carts and noticing if they're getting closer together.


It could be the case that there's some other bug that cause some of the carts to stop completely, which of course would result in the other, still-moving carts crashing.


Again, the timing here wasn't intended to be exact, so the exact spacing of carts is outside the bounds of what the system is supposed to support.

The fact that it works most of the time, and preserves spacing while you're looking, is a fluke more than anything else.

Will close this for now.  Please re-open if you have more info.

**Closed by jasonrohrer** 2020-05-12 20:57 UTC

**Comment by Nika50501** [comment] 2020-05-13 11:39
Alright, I'll try building another track and leaving bigger spacing between carts and see what happens. Ty for responding so fast.
