### ISSUE TITLE
Carts become derailed for mysterious reasons (reopened)

### ISSUE THREAD

**Issue by Nika50501** [jasonrohrer/OneLifeData7#790] opened 2020-05-13 18:09 UTC
I made a new railway system 72 blocks long and two blocks high that looped on itself and set down two carts on it that were about 60 seconds apart from one another. The carts were running smoothly until my death and I didn't notice any considerable shrinking of space between them (say for about 15 minutes). After I died, I came back to it in the next life in about 10-15 minutes and both of the carts were derailed next to each other.  The railway is setup in the current brown town with family name lord (on the west side next to the forge) on bigserver2. 

On a side-note. I know that a looping rail isn't intended behavior but it should be since we cannot yet "chain together" carts and one cart rails are not worth the investment. Making a long rail requires large investment of iron. So, to have a good payoff - having good item transport you need to have a lot of carts hence where looped rails come in. Having a large looping railway with multiple carts allows you to put items in each one and send it across the globe. Once you have 15+ carts on the rail, they become a better alternative than using a horse. You most certainly need multiple carts since horses move multiple times faster than carts (four times faster? six times faster? idk what the movements speed is) and move twice as many items in each go and can get sped up by 50% with a stone pathway.

**Comment by jasonrohrer** [comment] 2020-05-13 18:54
The benefit of the railway is that the human doesn't have to make the trip, so they save you time.  Well, assuming that there are two people working together on the two ends of the railway.

Sounds like you are using a loop for solo transport, where you load up the carts and then ride a horse to "beat" the carts to your destination?

Chained carts are beyond the scope of the engine, sadly...

Though I have thought about making larger-capacity carts.  I could make the current ones simply contain more, of course.

**Comment by jasonrohrer** [comment] 2020-05-13 18:56
Question:  when you came back to the tracks in the next life, did you walk there from somewhere else?  As in, you weren't born right near the tracks in the next life.

Question:  were there other people around in the Lord town during your absence?  Are you sure someone didn't dig up the track?

**Comment by jasonrohrer** [comment] 2020-05-13 19:29
I'm in Lord town as VOG right now, and I just fixed the carts via magic.  We'll have to see what happens to them....

**Comment by jasonrohrer** [comment] 2020-05-13 19:55
Wow, after kicking them into motion as VOG in the Lord village with the long, narrow loop, I came back about 30 minutes later, and they were both crashed in exactly the same spot as before.

That's totally wacky....

**Comment by jasonrohrer** [comment] 2020-05-13 20:54
Set it up again, and then popped back in about 20 minutes later.

The carts used to be VERY far apart (like on opposite sides of the track), but now they have completely caught up to each other.

Given my tests locally, I suspect this is due to people loading chunks of the map in that nearby area as they walk around, triggering one of the carts to move a second earlier than the other, here and there.

Unfortunately, I think that fixing the problem would be very expensive. When we load the map and look at a tile in the process, we ask whether it should decay into another state (if the decay time in the DB is stale).

If that tile is also being live tracked, allowing it to keep changing state on a timer even if no one is loading it again, then it kinda changes to the beat of its own drum, and everything is synced up.

The problem is that when we go to load a chunk of the map, we don't know if something is being live tracked or not.  Checking whether it is, for every tile that we load, would be very expensive.


Now, there might be a question about why, when looking at a map tile, we instantly apply a pending timed transition, if it's going to be live tracked anyway.  I don't know.... but that's a pretty deeply-integrated decision that I made a long time ago, and it would be very risky to try to change that now (because who knows what other bugs such a change would cause).

I will look at a way to stop them from crashing... why don't they just get backed up instead of crashing, if there's a cart in the way?

**Comment by Nika50501** [comment] 2020-05-14 04:15
> Question: when you came back to the tracks in the next life, did you walk there from somewhere else? As in, you weren't born right near the tracks in the next life.
> 
> Question: were there other people around in the Lord town during your absence? Are you sure someone didn't dig up the track?

Answers (probably no longer necessary): Yes, I moved there from white town to see it and yes there were players around it at the time.

> The benefit of the railway is that the human doesn't have to make the trip, so they save you time. Well, assuming that there are two people working together on the two ends of the railway.

Only bots can really achieve the level of coordination where one cart is beneficial since communication is so very limited in the game. In the given player-base you are better off just trying to visit the town and asking for supplies or doing it yourself, assuming you have a horse.

> I will look at a way to stop them from crashing... why don't they just get backed up instead of crashing, if there's a cart in the way?

Backing up carts sounds like a great idea. If you are able to startup carts from regular rails it would essentially have the same effect as chaining multiple carts in a single rail and will hopefully lead to better connected towns with more spread out cities. Maybe the carts can store directional values in them; that is, if eastward moving cart stops it becomes westward stopped cart and interacting with westward stopped cart will cause it to move westwards?

> Though I have thought about making larger-capacity carts. I could make the current ones simply contain more, of course.

My personal opinion is that having four items per cart and allowing multiple carts to pile up would be better balanced, since that way you need to invest in them and make multiple and only get good returns only if you invest at a large enough scale.

**Comment by jasonrohrer** [comment] 2020-05-14 20:09
Well, letting them pile up without crashing on a loop and letting them pile up on a linear track are two different things...

The problem is that when they pile up (instead of derailing), they are still waiting to keep moving in their original direction (they are just blocked).

So there's no way to send them in the other direction.... unless.... hmmm...

**Comment by jasonrohrer** [comment] 2020-05-14 20:26
Aha!  I found a way to make it work much better.

At any point, mid-journey, you can click any cart and reverse the direction.  You don't need to wait for it to get to the end.

Thus, if carts get backed up, or run into each other from opposite directions and stall, you can unstick them by reversing their direction.  Similarly, it will be possible to have a whole "train" of carts kinda moving together, if you send them all to one end to pile up and then reverse their direction at the same time.

**Comment by miskas9** [comment] 2020-05-14 21:00
could we have some baffs on Track Kit as well or greater storage on Carts ( like 6 or more).
Iron has been Nerfed so carts need an iron cost reduction as they are quite costly with the current Iron amounts.

**Closed** 2020-05-14 23:18 UTC
