### ISSUE TITLE
Different Dry Saplings behave differently

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#21] opened 2018-10-07 11:22 UTC
Dry Maple Sapling Cutting turns into a Hardened Row after ten minutes, while Dry Poplar, Yew, and Pine Sapling Cuttings don't have a timed transition.

Similarly, Dry Maple Saplings turn into a Dead Sapling after twenty minutes, while Dry Poplar, Yew, and Pine Saplings do not.

This might seem intentional but I don't think it is.

**Comment by jasonrohrer** [comment] 2018-10-08 16:29
This was caused by the same thing in the pattern code that was blocking dead dogs from decaying.  Fixed in  jasonrohrer/OneLife@8f6f3f7

**Closed by jasonrohrer** 2018-10-08 16:29 UTC
