### ISSUE TITLE
Property fence doors and every other door has to block animals getting trough.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#749] opened 2020-04-27 14:05 UTC
In reality, you don't need an airlock to stop animals from escaping Fences, you block them and you close the door. 
In-game you can't stop animals from walking through you so doors have to stop them. 

if you want us to close the doors add a 5-second transition that transforms open property doors from animal blocking to animal passable

**Comment by Spodnie** [comment] 2020-04-27 14:48
Animals would escape only because someone didn't close a door - that would happen all the time and therefore people would just remove doors to prevent it.

I mean, it would be a dead content if you had to close doors manually.

But if we had something like springy fence gates, that would be always blocking animals from going through, that would be cool.

Similar issue was posted in the past and Jason didn't like it, so I don't think anything will change now.

**Comment by jasonrohrer** [comment] 2020-04-27 21:43
So the suggestion here is that doors and gates, when open, should block animals from wandering out?

That's very easy with the +blocksMoving tag (which blocks animals from moving through, but not people).

And I hear you about the timer.... though that complicates things a little bit...

However, without a timer, people would just leave the gates open all the time, again making dead content (the closed gate would be dead).

Obviously, people close doors for other reasons (heat).

But fence gates, they'd just leave open all the time, I think.

Nobody's building "real" animal pen fences anyway these days, right?


There's also an important aesthetic that may be worth preserving---that of unruly animals that try to escape.  Waiting for a "good moment" to sneak out of a fence.

I know that people just use the "corner trick" to work around this anyway.

**Comment by Spodnie** [comment] 2020-04-27 22:07
I think the only solution that would make sense would be making springy fence gates (https://onetech.info/1851-Fence-Gate-wall-causeAutoOrient + steel spring) that would always block animals. They would work just like springy wooden doors, opening and closing automatically whenever someone is passing through, but animals could never pass them.

I don't know about the realism here, I don't know if people use springy gates in their gardens or whatever irl.
But I think this still could be better than all these "corner trick" pens.

**Comment by Spodnie** [comment] 2020-04-27 22:13
I mean, while it's not annoying to close doors irl, but it is annoying to do it in the game. It wouldn't be that bad if they were closing automatically (just imagine that we are closing them, but without doing any action) just to remove the annoyance.

**Comment by TwistedHBG** [comment] 2020-04-28 18:11
Currently both the open and closed gate are dead content because they can't actually function as pen gates. The problem is that (unless I am mistaken) animals teleport to an eligible tile and then play the walking animation. Just opening the gate for half a second is enough for the animal to path through it, even though their walking animation is not instant. In real life if you see an animal running towards an open door you can try shutting it, but that doesn't work in OHOL.

**Comment by laccy** [comment] 2020-04-29 03:00
Springy doors or the long-promised springy gates could block animals. Those will close anyway. Last time I checked they can go through.
Now with ropes, we can take them back so it's not a big issue. Other than bears. 

Front entrance with a rail door can block animals but takes away some space (has to be 5 long). Not many people understand or use front type entrances, they cost more and a bit more complex.

I think the corner trick is really unique to OHOL and has an old tradition. Making them takes skill and time so the reward for it is good enough.
Also, people did not realize that the new trick against bears is going inside the sheep pen. And city walls could be made like pens and be open but block bears the same time. They can kill you on items but they still limited on crossing them and can't change direction which is good I think.

There is a workaround just takes up quite a lot of space.
<img src="https://i.imgur.com/BffhcxG.png" alt="text">

Maybe allow us to make fences and way stones on the flooring.

**Comment by jasonrohrer** [comment] 2020-04-29 21:45
I hear you Twisted.  Yet another goofy consequence of the animals being map objects and not first-class citizens.

(Though the more I think about it, this is probably a good reason why the map can contain QUADRILLIONS of animals without any performance issues.)

I will make it so that regular fence gates (not property fences) auto-open and block animals (no spring needed).

**Comment by Spodnie** [comment] 2020-04-29 21:54
If you make gates not require springs to auto-open, most likely people will make pens made of only gates. Springs wouldn't be that bad.

**Closed** 2020-04-29 21:53 UTC
